name: menta-plexmediaserver
version: '1.14.1.5488-cc260c476'
summary: Your media on all your devices.
architectures: [amd64]
description: |
  Plex makes it possible to enjoy all of your media, whether in your living
  room, the car, or on a boat in the South Pacific!
  .
  You can manage your media by browsing to http://localhost:32400/manage

confinement: strict
grade: stable

apps:
  plexmediaserver:
    command: bin/wrapper.sh
    daemon: simple
    restart-condition: always
    plugs:
      - home
      - network
      - network-bind
      - removable-media

parts:
  plexmediaserver:
    plugin: dump
    source: https://downloads.plex.tv/plex-media-server/$SNAPCRAFT_PROJECT_VERSION/plexmediaserver_$SNAPCRAFT_PROJECT_VERSION_amd64.deb
    prepare: |
      rm -rf etc
      rm -rf lib
      rm -rf usr/sbin
      rm -rf usr/share/doc
      sed -i 's|Icon=plexmediamanager|Icon=/usr/share/pixmaps/plexmediamanager\.png|' usr/share/applications/plexmediamanager.desktop
  wrapper:
    plugin: dump
    source: files/
    prepare: |
      chmod +x bin/wrapper.sh
